# Generated by Django 2.2.5 on 2022-01-26 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park_location',
            fields=[
                ('location1', models.CharField(max_length=50)),
                ('location2', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Park_location',
            },
        ),
    ]
