# Generated by Django 2.2.5 on 2022-01-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_park_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Park_location',
        ),
    ]
