# Generated by Django 2.2.5 on 2022-01-26 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_delete_park_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='miniapp.City')),
            ],
            options={
                'db_table': 'Park',
            },
        ),
    ]
